### ISSUE TITLE
Broken - Does not appear to work with streaming queue on Mac

### ISSUE THREAD

**Issue by chris78664** [m5n/netflix-queue-sorter#4]
Downloaded and added to Firefox, Chrome and Safari after userscripts.org went off line and they appear to work for the DVD queue but not the Instant Queue (now called My List) it is just stuck "Retrieving Data" forever.

**Comment by linklisa** [comment]
Running v2.1o3 in Firefox, have also tried in Chrome.

Sorting by Star Rating works fine, if I'm sorting the whole queue. But not if I choose "Only apply sort to rows..." In either case, I'm used to getting the message to go back a screen, and reloading once or twice before the titles appear sorted. Now, a reload only puts one more title in sort order.

**Comment by m5n** [comment]
Thx, @linklisa, for opening a new issue #5 for this.
