### ISSUE TITLE
Doesn't function with UK site using my out of the ordinary account setup

### ISSUE THREAD

**Issue by DogEyedBoy** [m5n/netflix-queue-sorter#6]
I'll provide a quick rundown of how my account is setup because I believe that's the cause of my issue.

I live in the UK, but I created a US Netflix account years ago by changing my DNS settings because I wanted the queue feature. I've been happily using my queue and Netflix Queue Sorter for some time while switching between UK and US Netflix with a DNS change when needed.

Recently I noticed UK Netflix was giving me the option to add things to my "list", I added a few things then checked the Netflix website, and there _was_ a list. The list available from the UK Netflix page consisted of the items I'd added when on the US page or app that were also available in the UK and the few items I'd added when on the UK app that were exclusive to the UK.

Great, I thought, but Netflix Queue Sorter will not function when I'm on the UK Netflix page, it'll just display [Retrieving data...] forever.

Any idea how this can be fixed?

**Comment by m5n** [comment]
I probably need to add the UK Netflix URL to the script, what's the URL when you're on the List page?

**Comment by DogEyedBoy** [comment]
Exactly the same as when I switch to the US one: http://www.netflix.com/MyList?leid=595&link=subnav

**Comment by m5n** [comment]
Can you go to the details page for a movie in your list? Perhaps that URL is different from the US one?

**Comment by DogEyedBoy** [comment]
3rd Rock from the Sun UK: http://www.netflix.com/WiMovie/70157523?trkid=13641790

3rd Rock from the Sun US: http://www.netflix.com/WiMovie/70157523?trkid=50279657

**Comment by m5n** [comment]
Does sort by start rating work? (Trying to avoid it going off retrieving data.)
If so, try changing the movie details URL in the script options (click the wrench icon) to:

```
 http://{hostName}/WiMovie/{movieId}
```

(Please capture the original value first, so you can restore if that also does not work.)

**Comment by DogEyedBoy** [comment]
Shuffle and Reverse work, everything else gets stuck on "Retrieving data..."

I can't get anything to stay saved in the options.

**Comment by m5n** [comment]
That's interesting. Which browser & OS are you using?

**Comment by DogEyedBoy** [comment]
Chrome, Windows 7.

**Comment by m5n** [comment]
For Chrome to remember the settings, it uses the browser's "local storage" (due to [this bug](https://code.google.com/p/chromium/issues/detail?id=33089)). I believe for this to work your browser must be allowed to "remember history".  Could you see if your browser is configured that way, or temporarily allow it to see if that works?

**Comment by DogEyedBoy** [comment]
I'm not sure how to do that.

**Comment by m5n** [comment]
With Chrome 43.0:
- Click the Chrome menu (the three stripes underneath each other)
- Select "Settings"
- At the bottom, click on the "Show advanced settings" link
- Under "Privacy", click the "Content settings" button
- Make sure the "Allow local data to be set" options is selected
- See if the "Block third-party cookies and site data" box checked or not (may need that later).
- Click "Done"

Chrome may need to restart. If you can, go ahead and restart Chrome. Try it again.

If it still doesn't work, and the "Block third-party cookies and site data" box was checked, try unchecking it, restarting Chrome and trying again.

If that still doesn't work, on the Netflix List page, click on the wrench tool icon that is part of the Netflix Queue Sorter script UI. Enable debug mode and save. Reload the Netflix List page.
Once loaded, type Ctrl-Shift-J to bring up the JavaScript console. Is there any output there? If not, with the console open, reload the page again and see if output appears.

Sorry to make you do all of this, hopefully a clue to what's wrong will be revealed.

**Comment by DogEyedBoy** [comment]
"Allow local data to be set" is already set, "Block third-party cookies and site data" is unchecked.

Checking "Enable debug mode" suffers from the same issue as every other setting, on a page refresh it's no longer set.

Console displays this:

Tampermonkey started VM1385:3845
Uncaught Parse error {"readyState":4,"responseHeaders":"","finalUrl":"http://userscripts.org/scripts/source/35183.meta.js","status":0,"statusText":"","responseXML":null,"responseText":"","response":null}
versionCheckHandler @ VM1385:3845
(anonymous function) @ VM1318:41

**Comment by m5n** [comment]
Oops, forgot about the settings not saving! :)
OK, so all looks good on your end (the check-for-script-update error is expected). I'll play around with Chrome / the script and see if I can reproduce this.
