### ISSUE TITLE
update queue broken

### ISSUE THREAD

**Issue by lucidquasar** [m5n/netflix-queue-sorter#7]
When I sort by star rating in both my list and dvd queue it directs me to a netflix page error after attempting to auto sort list. hitting the back button will take me back to my queue with new order numbers listed next to each title but there's no way to update the queue to put them in the right order because the button  for update list is grayed out.

**Comment by flixaddict87** [comment]
I think the issue has something to do with the way Netflix handles the re-sort "orders". I've been sorting every which way to Sunday, literally, on my maxed out lists, and I get mostly errors and sometimes a partial sort works. So yeah I think I have an explanation and solution, but I don't know anything about script so pardon any ignorance I'm about to spiel from my fingers in advance. I think that the days of queue hoarding are over. No matter who's current update of the script I use if the sort is pretty much a complete rearrange over so many titles it'll crap out. When I create a slim list and boom works fine. Around 300 i'd say could go either way, I have not found a constant outside of keeping the list under 100. So yeah keep it slim, watched it and drop it. The script is included in Flix Plus by Lifehacker, so keeping it slim wouldn't be an issue for Mylist, and the extension pretty much has every Netflix extension, like it helps you Identify what's been watched or rated. However I don't think it works on DVD, but who cares DVD knocks that stuff out for you plus what's in your queue automatically. So really finding stuff to add won't be a problem. it's committing to the watching that's the real challenge. I got like 50 shows I've been wanting to watch but spend so much time o.c.d.-ing my list they are now in their 3rd or more seasons or have been dropped by Netflix. So yeah get Flix Plus by Lifehacker, Tampermonky or grease monkey with the raw script from here and switch between the two. If you want to get the links and trailer stuff on the dvd site use "Netflix Enhancer - Old" and switch that on and off too.

**Comment by m5n** [comment]
@lucidquasar, for now, just reload the page once you're back at the list page. The sort or some of the sort hopefully took effect. I'll investigate a fix as part of issue #5, so let's continue the discussion there.

@flixaddict87, yup, a large number of order changes seems to cause the error... in theory I could make the script send the updates in batches, sorting only a few rows at a time. I'll look into that.
